config/routes.rb
Rails.application.routes.draw do
  resources :blogs
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  def index
    @blogs = Blog.all
  end

  def show
  end

  def new
    @blog = Blog.new
  end

  def edit
  end

  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.haml
= form_for @blog do |f|
  - if @blog.errors.any?
    #error_explanation
      %h2= "#{pluralize(@blog.errors.count, "error")} prohibited this blog from being saved:"
      %ul
        - @blog.errors.full_messages.each do |message|
          %li= message

  .field.form-group
    = f.label :title
    = f.text_field :title, class: "form-control"
  .field.form-group
    = f.label :description
    = f.text_field :description, class: "form-control"
  .actions
    = f.submit 'Save', class: "btn btn-primary"

app/views/blogs/edit.html.haml
%h1 Editing blog

= render 'form'

= link_to 'Show', @blog, class: "btn btn-link"
\|
= link_to 'Back', blogs_path, class: "btn btn-link"

app/views/blogs/index.html.haml
%h1 Listing blogs

%table.table
  %thead
    %tr
      %th Title
      %th Description
      %th
      %th
      %th

  %tbody
    - @blogs.each do |blog|
      %tr
        %td= blog.title
        %td= blog.description
        %td= link_to 'Show', blog, class: "btn btn-link"
        %td= link_to 'Edit', edit_blog_path(blog), class: "btn btn-link"
        %td= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link"

%br

= link_to 'New Blog', new_blog_path, class: "btn btn-primary"

app/views/blogs/new.html.haml
%h1 New blog

= render 'form'

= link_to 'Back', blogs_path, class: "btn btn-link"

app/views/blogs/show.html.haml
%h1 Show blog

.row
  %p.col-3
    %b Title
  %p.col
    = @blog.title
.row
  %p.col-3
    %b Description
  %p.col
    = @blog.description

= link_to 'Edit', edit_blog_path(@blog), class: "btn btn-link"
\|
= link_to 'Back', blogs_path, class: "btn btn-link"

app/views/layouts/application.html.haml
!!!
%html{lang: "ja"}
  %head
    %meta{charset: "utf-8"}
    %meta{name: "viewport", content: "width=device-width, initial-scale=1, shrink-to-fit=no"}
    %title Bootstrap4
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %nav.navbar.navbar-expand-lg.navbar-dark.bg-primary
      %a.navbar-brand{:href => blogs_path} Rails Bootstrap4 Sample
      %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
        %span.navbar-toggler-icon
      #navbarSupportedContent.collapse.navbar-collapse
        %ul.navbar-nav.mr-auto
          %li.nav-item.active
            %a.nav-link{:href => "#"}
              Home
              %span.sr-only (current)
          %li.nav-item
            %a.nav-link{:href => "#"} Link
          %li.nav-item.dropdown
            %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              Dropdown
            .dropdown-menu{"aria-labelledby" => "navbarDropdown"}
              %a.dropdown-item{:href => "#"} Action
              %a.dropdown-item{:href => "#"} Another action
              .dropdown-divider
              %a.dropdown-item{:href => "#"} Something else here
          %li.nav-item
            %a.nav-link.disabled{"aria-disabled" => "true", :href => "#", :tabindex => "-1"} Disabled
        %form.form-inline.my-2.my-lg-0
          %input.form-control.mr-sm-2{"aria-label" => "Search", :placeholder => "Search", :type => "search"}/
          %button.btn.btn-outline-success.my-2.my-sm-0{:type => "submit"} Search

    - if notice.presence
      .alert.alert-primary
        %p#notice= notice

    .container
      = yield